In [1]:
import pandas as pd
import geopandas as gpd
from pathlib import Path

In [2]:
county_boundary = gpd.read_file("../data/processed/county_boundary.shp")
county_boundary.head()

,STATEFP,COUNTYFP,TRACTCE,GEOIDFQ,GEOID,NAME,NAMELSAD,STUSPS,NAMELSADCO,STATE_NAME,LSAD,ALAND,AWATER,geometry
0,16,055,001901,1400000US16055001901,16055001901,19.01,Census Tract 19.01,ID,Kootenai County,Idaho,CT,1136651855,20841605,"POLYGON ((496918.961 5271680.234, 496910.542 5..."

In [3]:
# Make sure it is projected coordinate 
county_boundary.crs

<Projected CRS: EPSG:26911>
Name: NAD83 / UTM zone 11N
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: North America - between 120°W and 114°W - onshore and offshore. Canada - Alberta; British Columbia; Northwest Territories; Nunavut. United States (USA) - California; Idaho; Nevada, Oregon; Washington.
- bounds: (-120.0, 30.88, -114.0, 83.5)
Coordinate Operation:
- name: UTM zone 11N
- method: Transverse Mercator
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [4]:
shp_path = Path("../data/raw/place")
shp_file = next(shp_path.glob("*.shp"))
places = gpd.read_file(shp_file)
places.head()

,STATEFP,PLACEFP,PLACENS,GEOIDFQ,GEOID,NAME,NAMELSAD,STUSPS,STATE_NAME,LSAD,ALAND,AWATER,geometry
0,16,34930,02410697,1600000US1634930,1634930,Hansen,Hansen city,ID,Idaho,25,903899,0,"POLYGON ((-114.30594 42.53688, -114.29864 42.5..."
1,16,39070,02410802,1600000US1639070,1639070,Huetter,Huetter city,ID,Idaho,25,117471,0,"POLYGON ((-116.85411 47.70502, -116.85161 47.7..."
2,16,27460,02410495,1600000US1627460,1627460,Ferdinand,Ferdinand city,ID,Idaho,25,452353,0,"POLYGON ((-116.39491 46.15449, -116.38965 46.1..."
3,16,67870,02410949,1600000US1667870,1667870,Riggins,Riggins city,ID,Idaho,25,1029902,123855,"POLYGON ((-116.32982 45.4122, -116.32138 45.41..."
4,16,16750,02410187,1600000US1616750,1616750,Coeur d'Alene,Coeur d'Alene city,ID,Idaho,25,43691994,1976736,"POLYGON ((-116.85288 47.70099, -116.85096 47.7..."

In [5]:
places = places.to_crs(county_boundary.crs)
places.crs

<Projected CRS: EPSG:26911>
Name: NAD83 / UTM zone 11N
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: North America - between 120°W and 114°W - onshore and offshore. Canada - Alberta; British Columbia; Northwest Territories; Nunavut. United States (USA) - California; Idaho; Nevada, Oregon; Washington.
- bounds: (-120.0, 30.88, -114.0, 83.5)
Coordinate Operation:
- name: UTM zone 11N
- method: Transverse Mercator
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [6]:
kootenai_places = gpd.clip(places, county_boundary)
kootenai_places

,STATEFP,PLACEFP,PLACENS,GEOIDFQ,GEOID,NAME,NAMELSAD,STUSPS,STATE_NAME,LSAD,ALAND,AWATER,geometry
38,16,17830,02585569,1600000US1617830,1617830,Conkling Park,Conkling Park CDP,ID,Idaho,57,2705973,0,"POLYGON ((517018.408 5250112.31, 517497.512 52..."
47,16,88480,02412309,1600000US1688480,1688480,Worley,Worley city,ID,Idaho,25,502488,0,"POLYGON ((505881.753 5250288.637, 506273.483 5..."
217,16,35200,02410708,1600000US1635200,1635200,Harrison,Harrison city,ID,Idaho,25,9231198,2176062,"MULTIPOLYGON (((517587.951 5257215.899, 517660..."
162,16,68950,02585592,1600000US1668950,1668950,Rockford Bay,Rockford Bay CDP,ID,Idaho,57,9778278,0,"POLYGON ((506518.161 5261806.717, 506428.501 5..."
22,16,27550,02410496,1600000US1627550,1627550,Fernan Lake Village,Fernan Lake Village city,ID,Idaho,25,197627,2689,"POLYGON ((518702.482 5279839.263, 518860.284 5..."
4,16,16750,02410187,1600000US1616750,1616750,Coeur d'Alene,Coeur d'Alene city,ID,Idaho,25,43691994,1976736,"POLYGON ((511182.052 5283066.24, 511182.026 52..."
1,16,39070,02410802,1600000US1639070,1639070,Huetter,Huetter city,ID,Idaho,25,117471,0,"POLYGON ((511131.877 5283526.82, 511179.376 52..."
208,16,77050,02411974,1600000US1677050,1677050,State Line,State Line city,ID,Idaho,25,285215,0,"POLYGON ((497046.14 5283452.781, 497068.642 52..."
48,16,64810,02411475,1600000US1664810,1664810,Post Falls,Post Falls city,ID,Idaho,25,49621216,70897,"MULTIPOLYGON (((508530.246 5285326.007, 508530..."
182,16,20350,02410289,1600000US1620350,1620350,Dalton Gardens,Dalton Gardens city,ID,Idaho,25,6168849,13365,"POLYGON ((515988.725 5287488.891, 515988.6 528..."
105,16,35830,02410714,1600000US1635830,1635830,Hauser,Hauser city,ID,Idaho,25,3139018,0,"MULTIPOLYGON (((498894.397 5289619.552, 498900..."
192,16,36460,02410722,1600000US1636460,1636460,Hayden Lake,Hayden Lake city,ID,Idaho,25,1582674,449680,"POLYGON ((517587.99 5289930.194, 517597.043 52..."
86,16,36370,02410721,1600000US1636370,1636370,Hayden,Hayden city,ID,Idaho,25,27493579,39037,"MULTIPOLYGON (((517608.304 5291137.038, 517606..."
185,16,66340,02411521,1600000US1666340,1666340,Rathdrum,Rathdrum city,ID,Idaho,25,18011197,0,"POLYGON ((506323.089 5293788.816, 506315.717 5..."
88,16,03700,02409748,1600000US1603700,1603700,Athol,Athol city,ID,Idaho,25,2973317,0,"POLYGON ((521291.301 5311346.254, 521325.215 5..."
130,16,76060,02411953,1600000US1676060,1676060,Spirit Lake,Spirit Lake city,ID,Idaho,25,6361203,0,"POLYGON ((508343.714 5313796.381, 508346.31 53..."

In [7]:
kootenai_places.shape

(16, 13)

In [8]:
kootenai_places = kootenai_places.rename(columns={"NAME": "city"})

In [12]:
kootenai_places.to_file("../data/processed/kootenai_cities.gpkg", driver="GPKG")

In [ ]:
stores_points = gpd.read_file("../data/processed/grocery_store_points.gpkg")

In [ ]:
ax = county_boundary.plot(
    facecolor="none",
    edgecolor="black"
)

kootenai_places.plot(
    ax=ax,
    facecolor="none",
    edgecolor="blue"
)

stores_points.plot(
    ax=ax,
    markersize=10
)

# Label cities
for idx, row in kootenai_places.iterrows():
    x = row.geometry.centroid.x
    y = row.geometry.centroid.y

    ax.annotate(
        row["city"],
        (x, y),
        fontsize=8
    )

In [ ]:
# spacial join 
stores_with_city = gpd.sjoin(
    stores_points,
    kootenai_places[["city", "geometry"]],
    predicate="within"
)

In [ ]:
# fill store city nan values 
stores_with_city["addr:city"] = (
    stores_with_city["addr:city"]
    .fillna(stores_with_city["city"])
)

In [ ]:
print(stores_with_city.columns)

In [ ]:
stores_with_city.to_file(
    "../data/processed/stores_points_with_cities.gpkg",
    driver="GPKG")