In [ ]:
import geopandas as gpd
import osmnx as ox 
from pathlib import Path

In [ ]:
print(Path.cwd())

d:\Wu\2026\Project Portfolio\002 Project\grocery_access

In [5]:
G = ox.load_graphml("data/processed/kootenai_drive.graphml")

In [6]:
stores = gpd.read_file("data/processed/stores_points_with_cities.gpkg")

In [8]:
stores.columns

Index(['element', 'id', 'addr:city', 'addr:housenumber', 'addr:postcode',
       'addr:street', 'name', 'opening_hours', 'shop', 'brand',
       'brand:wikidata', 'official_name', 'addr:state', 'phone', 'website',
       'contact:facebook', 'start_date', 'building', 'designation',
       'addr:country', 'operator', 'operator:wikidata', 'payment:app:walmart',
       'payment:apple_pay', 'payment:google_pay', 'payment:samsung_pay', 'ref',
       'ref:walmart', 'sensory_friendly:accommodation',
       'sensory_friendly:conditional', 'source', 'source:name', 'layer',
       'toilets', 'branch', 'internet_access', 'organic', 'toilets:wheelchair',
       'wheelchair', 'building:levels', 'not:brand:wikidata', 'payment:cash',
       'payment:cheque', 'payment:contactless', 'payment:credit_cards',
       'payment:debit_cards', 'payment:ebt', 'geometry_type', 'index_right',
       'city', 'geometry'],
      dtype='str')

In [12]:
len(stores)

30

In [11]:
stores[["name", "addr:city", "city", "addr:street", "geometry_type", "geometry"]].sort_values(["name"])

,name,addr:city,city,addr:street,geometry_type,geometry
4,Albertsons,Hayden,Hayden,West Prairie Avenue,Point,POINT (515814.247 5288108.75)
5,C & C Grocery,Coeur d'Alene,Coeur d'Alene,NaN,Point,POINT (512703.314 5287894.661)
3,Flour Mill Natural Foods,Hayden,Hayden,West Commerce Drive,Point,POINT (515911.85 5288856.19)
12,Fred Meyer,Coeur d'Alene,Coeur d'Alene,West Kathleen Avenue,Polygon,POINT (515390.535 5284361.564)
26,Gittel's Grocery,Coeur d'Alene,Coeur d'Alene,NaN,Polygon,POINT (516013.751 5281469.361)
0,Grocery Outlet,Coeur d'Alene,Coeur d'Alene,NaN,Point,POINT (515496.942 5283616.399)
28,Grocery Outlet,Post Falls,Post Falls,North Highway 41,Polygon,POINT (508084.904 5286507.542)
11,Harrison Trading Company,Harrison,Harrison,NaN,Polygon,POINT (516148.496 5255651.677)
27,Jordan's Grocery,Coeur d'Alene,Coeur d'Alene,NaN,Polygon,POINT (517671.934 5281126.706)
9,Lakeside Harvest Foods,Coeur d'Alene,Coeur d'Alene,NaN,Polygon,POINT (517393.444 5280087.921)
1,Little Town Market,Athol,Athol,East Highway 54,Point,POINT (522224.559 5310579.98)
19,Miller's Harvest Foods,Spirit Lake,Spirit Lake,NaN,Polygon,POINT (509885.53 5312176.395)
15,Natural Grocers,Coeur d'Alene,Coeur d'Alene,West Neider Avenue,Polygon,POINT (515692.12 5283672.407)
24,Pilgrim's Market,Coeur d'Alene,Coeur d'Alene,North 4th Street,Polygon,POINT (516502.884 5281603.999)
25,Safeway,Coeur D'Alene,Coeur d'Alene,North 4th Street,Polygon,POINT (516376.469 5281101.996)
10,Safeway,Coeur d'Alene,Coeur d'Alene,Ironwood Drive,Polygon,POINT (515774.478 5282270.684)
6,Safeway,Coeur d'Alene,Coeur d'Alene,West Neider Avenue,Polygon,POINT (515918.442 5283954.018)
23,Super One Foods,Coeur d'Alene,Coeur d'Alene,West Kathleen Avenue,Polygon,POINT (515715.468 5284797.707)
18,Super One Foods,Athol,Athol,NaN,Polygon,POINT (522899.422 5310822.387)
13,Super One Foods,Rathdrum,Rathdrum,NaN,Polygon,POINT (509226.711 5295819.771)
21,Super One Foods,Post Falls,Post Falls,NaN,Polygon,POINT (504774.694 5284693.603)
2,Target,Coeur d'Alene,Coeur d'Alene,West Canfield Avenue,Point,POINT (515630.739 5286884.796)
29,Trader Joe's,Coeur d'Alene,Coeur d'Alene,East Spokane Avenue,Polygon,POINT (516392.303 5281636.644)
22,US Foods Chef's Store,Coeur d'Alene,Coeur d'Alene,East Appleway Avenue,Polygon,POINT (516254.406 5282948.547)
17,Walmart Supercenter,Hayden,Hayden,West Honeysuckle Avenue,Polygon,POINT (515494.044 5288430.484)
8,Walmart Supercenter,Post Falls,Post Falls,West Pointe Parkway,Polygon,POINT (497685.352 5283413.098)
7,Walmart Supercenter,Post Falls,Post Falls,East Mullan Avenue,Polygon,POINT (506971.509 5284494.234)
20,Wenig Foods,Post Falls,Post Falls,North Corbin Road,Polygon,POINT (500644.279 5284940.87)
14,WinCo Foods,Coeur d'Alene,Coeur d'Alene,W Appleway Ave,Polygon,POINT (514586.735 5283407.051)
16,Yoke's,Post Falls,Post Falls,East Seltice Way,Polygon,POINT (505557.085 5284263.008)

In [14]:
stores.crs

<Projected CRS: EPSG:26911>
Name: NAD83 / UTM zone 11N
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: North America - between 120°W and 114°W - onshore and offshore. Canada - Alberta; British Columbia; Northwest Territories; Nunavut. United States (USA) - California; Idaho; Nevada, Oregon; Washington.
- bounds: (-120.0, 30.88, -114.0, 83.5)
Coordinate Operation:
- name: UTM zone 11N
- method: Transverse Mercator
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [16]:
# OpenStreeMap uses WGS84 (4326)
stores = stores.to_crs(4326)

In [17]:
stores['x'] = stores.geometry.x
stores['y'] = stores.geometry.y

In [19]:
stores["nearest_node"] = ox.distance.nearest_nodes(
    G,
    stores['x'],
    stores['y']
)

In [20]:
stores[["name", "addr:city", "nearest_node"]]

                        name      addr:city  nearest_node
0             Grocery Outlet  Coeur d'Alene    8556346272
1         Little Town Market          Athol     129848349
2                     Target  Coeur d'Alene    8638420764
3   Flour Mill Natural Foods         Hayden     129845848
4                 Albertsons         Hayden     129776037
5              C & C Grocery  Coeur d'Alene     129721878
6                    Safeway  Coeur d'Alene     129865809
7        Walmart Supercenter     Post Falls     130527991
8        Walmart Supercenter     Post Falls     365216968
9     Lakeside Harvest Foods  Coeur d'Alene     129825158
10                   Safeway  Coeur d'Alene    9551752160
11  Harrison Trading Company       Harrison     129727061
12                Fred Meyer  Coeur d'Alene     129785875
13           Super One Foods       Rathdrum    6548780367
14               WinCo Foods  Coeur d'Alene     130527024
15           Natural Grocers  Coeur d'Alene   10049402943
16                    Yoke's     Post Falls     129901690
17       Walmart Supercenter         Hayden    6111377794
18           Super One Foods          Athol     129686869
19    Miller's Harvest Foods    Spirit Lake     129718035
20               Wenig Foods     Post Falls     129852977
21           Super One Foods     Post Falls     129715074
22     US Foods Chef's Store  Coeur d'Alene     130528273
23           Super One Foods  Coeur d'Alene     129905328
24          Pilgrim's Market  Coeur d'Alene     130657374
25                   Safeway  Coeur D'Alene     129697439
26          Gittel's Grocery  Coeur d'Alene    3540771715
27          Jordan's Grocery  Coeur d'Alene     129856015
28            Grocery Outlet     Post Falls    2423249776
29              Trader Joe's  Coeur d'Alene     129879891

In [21]:
stores.to_file("data/processed/stores_nearest_nodes.gpkg", driver="GPKG")